name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        cd app
        npm install

    - name: Build Docker image
      run: |
        docker build -t todo-app -f docker/Dockerfile .

    - name: Verify Docker image created
      run: docker images
